### ISSUE TITLE
CLI args shouldn't be parsed when importing package

### ISSUE THREAD

**Issue by davidrissato** [auth0/auth0-deploy-cli#176]
### Description

`args.argv` should only be invoked when `require.main === module` is true, otherwise a simple require to this module will parse command line arguments unexpectedly.
This is specially harmful when you are importing this package at the top of your module and trying to create your own set of command line options.

### Reproduction

Create a node.js file importing this package:
*my_test.js*
```javascript
const Auth0 = require('auth0-deploy-cli');

console.log('CLI arguments: ' + process.argv);
```

Invoke this file using node:
`node my_test.js --help`

That shouldn't show `auth0-deploy-cli` help.

Fix suggestion here: https://github.com/davidrissato/auth0-deploy-cli/commit/ff4104168c47f24d60a10bee9c11e32b8ec4d6ef

### Environment

- **Version of this library used:** 3.6.1
- **Version of the platform or framework used, if applicable:**
- **Other relevant versions (language, server software, OS, browser):**
- **Other modules/plugins/libraries that might be involved:**

**Comment by aepsil0n** [comment]
To whom it may concern, I've worked around this issue by removing arguments from `process.argv`.

**Comment by TranquilMarmot** [comment]
Yeah, we had to work around this by doing something like....

```js
const backupArgv = [...process.argv];
process.argv = [];
const dump = require('auth0-deploy-cli').dump;
process.argv = backupArgv;
```

FWIW it looks like this is fixed in the v4 beta of this library, although that also calls out to `/v2/hooks` which I think isn't turned on yet

**Comment by shushen** [comment]
> Fix suggestion here: [davidrissato@ff41041](https://github.com/davidrissato/auth0-deploy-cli/commit/ff4104168c47f24d60a10bee9c11e32b8ec4d6ef)

@davidrissato Thanks for reporting the issue and the fix looks great. Would you like to submit a PR?

**Comment by davidrissato** [comment]
> > Fix suggestion here: [davidrissato@ff41041](https://github.com/davidrissato/auth0-deploy-cli/commit/ff4104168c47f24d60a10bee9c11e32b8ec4d6ef)
> 
> @davidrissato Thanks for reporting the issue and the fix looks great. Would you like to submit a PR?

Sure, glad to do that.

**Comment by aaronchilcott** [comment]
@shushen @davidrissato, I ran in to this issue myself recently when I upgraded node from 8 to 13. I haven't investigate why this has occurred, however. 
I see that @davidrissato hasn't yet had time to create a PR, so - since I have a dependency on this fix being in place - I've gone ahead and created a PR with what I hope is an adequate fix.

**Comment by davidrissato** [comment]
Sorry guys, I realized that I forgot to create this PR. Let me do that.

**Comment by shawnmclean** [comment]
Fix released in https://github.com/auth0/auth0-deploy-cli/releases/tag/v4.0.3

**Comment by mscoobby** [comment]
The issue is still present in https://github.com/auth0/auth0-deploy-cli/releases/tag/v5.0.0.
### Description
I'm building a CLI support for an electron application which uses auth0-deploy-cli as a library. Running the help command results in help output from both auth0-deply-cli and my cli (I'm using yargs aswell) the issue is not present on v4.0.3.
I'm importing the library like that:
```import { deploy, IAuth0CliConfig } from 'auth0-deploy-cli'```

### Environment
Version of this library used: 5.0.0
Other relevant versions (language, server software, OS, browser):

- Node 12.16.1

- Yargs 15.3.1
