### ISSUE TITLE
Hooks fail to export

### ISSUE THREAD

**Issue by lorenh** [auth0/auth0-deploy-cli#203]
### Description

When I run this to export a tenant to directory structure

a0deploy export -c config-dev.json -f directory -o dev

:
2020-02-04T00:46:36.730Z - error: Problem exporting hooks

### Reproduction

a0deploy export -c config-dev.json -f directory -o dev

2020-02-04T00:46:21.657Z - info: Loading Auth0 Tenant Data
2020-02-04T00:46:21.659Z - info: Retrieving rules data from Auth0
2020-02-04T00:46:22.072Z - info: Retrieving rulesConfigs data from Auth0
2020-02-04T00:46:22.470Z - info: Retrieving hooks data from Auth0
2020-02-04T00:46:23.781Z - info: Retrieving pages data from Auth0
2020-02-04T00:46:24.628Z - info: Retrieving resourceServers data from Auth0
2020-02-04T00:46:25.047Z - info: Retrieving clients data from Auth0
2020-02-04T00:46:25.573Z - info: Retrieving databases data from Auth0
2020-02-04T00:46:26.025Z - info: Retrieving connections data from Auth0
2020-02-04T00:46:26.457Z - info: Retrieving tenant data from Auth0
2020-02-04T00:46:26.864Z - info: Retrieving emailProvider data from Auth0
2020-02-04T00:46:27.268Z - info: Retrieving emailTemplates data from Auth0
2020-02-04T00:46:34.431Z - info: Retrieving clientGrants data from Auth0
2020-02-04T00:46:34.865Z - info: Retrieving guardianFactors data from Auth0
2020-02-04T00:46:35.320Z - info: Retrieving guardianFactorProviders data from Auth0
2020-02-04T00:46:35.785Z - info: Retrieving guardianFactorTemplates data from Auth0
2020-02-04T00:46:36.203Z - info: Retrieving roles data from Auth0
2020-02-04T00:46:36.635Z - info: Retrieving branding data from Auth0
2020-02-04T00:46:36.635Z - info: Retrieving prompts data from Auth0
2020-02-04T00:46:36.639Z - info: Writing {rules}...
2020-02-04T00:46:36.648Z - info: Writing {pages}...
2020-02-04T00:46:36.648Z - info: Writing {database-connection}...
2020-02-04T00:46:36.648Z - info: Writing {grants}...
2020-02-04T00:46:36.648Z - info: Writing {resource-servers}...
2020-02-04T00:46:36.648Z - info: Writing {clients}...
2020-02-04T00:46:36.648Z - info: Writing {connections}...
2020-02-04T00:46:36.716Z - info: Writing tenant.json
2020-02-04T00:46:36.648Z - info: Writing {connections}...
2020-02-04T00:46:36.648Z - info: Writing {emails}...
2020-02-04T00:46:36.648Z - info: Writing {guardian}...
2020-02-04T00:46:36.730Z - error: Problem running command export
2020-02-04T00:46:36.730Z - error: Problem exporting hooks

### Environment
using 4.0.0

**Comment by lorenh** [comment]
Here's an interesting twist though... just tried exporting with YAML format and it worked, so it seems it may be related to the directory format.

**Comment by lorenh** [comment]
I understand this was fixed by 4.0.1.  I don't think it's an issue anymore.

**Comment by dominicfallows** [comment]
This is still a problem for me on `4.0.1` when exporting to directory format

**Comment by dominicfallows** [comment]
I opened a new issue: https://github.com/auth0/auth0-deploy-cli/issues/208
