### ISSUE TITLE
Schema validation for webauthn-roaming in guardianFactors

### ISSUE THREAD

**Issue by lorenh** [auth0/auth0-deploy-cli#288]
Using version 5.3.0 I exported YAML from our tenants and it added the following under guardianFactors:

```
guardianFactors:
    :
  - name: webauthn-roaming
    enabled: false
```

Yet when I try to import that back into I receive a schema validation error

```
2020-11-10T23:54:36.039Z - error: Problem running command import
2020-11-10T23:54:36.040Z - error: Schema validation failed loading [
    {
        "keyword": "enum",
        "dataPath": ".guardianFactors[5].name",
        "schemaPath": "#/properties/guardianFactors/items/properties/name/enum",
        "params": {
            "allowedValues": [
                "sms",
                "push-notification",
                "otp",
                "email",
                "duo"
            ]
        },
        "message": "should be equal to one of the allowed values"
    }
]
```

If I remove the new webauthn-roaming setting it imports succesfully.

**Comment by titenkov** [comment]
We experience the same issue...

**Comment by yvovandoorn** [comment]
@titenkov and @lorenh 5.3.1 should resolve this as the underlying dependency, https://github.com/auth0-extensions/auth0-source-control-extension-tools/, has been updated to include this.

**Comment by shushen** [comment]
Thanks @yvovandoorn! Yes, v5.3.1 should have solved this issue.

**Comment by tyroneerasmus** [comment]
Is this solved for everyone else? I am still seeing this on `v5.3.2`

YAML config snippet:
```
guardianFactors:
  - name: duo
    enabled: false
  - name: email
    enabled: false
  - name: otp
    enabled: true
  - name: push-notification
    enabled: false
  - name: sms
    enabled: false
  - name: webauthn-roaming
    enabled: true
```

throws:

```
2021-01-04T07:54:21.259Z - error: Problem running command import
2021-01-04T07:54:21.260Z - error: Schema validation failed loading [
    {
        "keyword": "enum",
        "dataPath": ".guardianFactors[5].name",
        "schemaPath": "#/properties/guardianFactors/items/properties/name/enum",
        "params": {
            "allowedValues": [
                "sms",
                "push-notification",
                "otp",
                "email",
                "duo"
            ]
        },
        "message": "should be equal to one of the allowed values"
    }
]
```

**Comment by tyroneerasmus** [comment]
Ignore me, looks like this was resolved in `v.5.4.0`

**Comment by rodrigoreis22** [comment]
I'm seeing this error on v5.5.6
