### ISSUE TITLE
AUTH0_KEYWORD_REPLACE_MAPPINGS not working in database-connections files and rules

### ISSUE THREAD

**Issue by xurei** [auth0/auth0-deploy-cli#3]
I would like to configure a domain in the replace mappings to inject it in JS files (rules and custom database scripts). However, it doesn't seem to work.
Here is my config :
```
{
    "AUTH0_DOMAIN": "mydomain.auth0.com",
    "AUTH0_CLIENT_ID": "xxxxxxxxxxxxxxxxxxxxxxxxx",
    "AUTH0_CLIENT_SECRET": "xxxxxxxxxxxxxxxxxxxxx",
    "AUTH0_KEYWORD_REPLACE_MAPPINGS": {
        "PG_DOMAIN": "https://99db6f1c.ngrok.io"
    }
}
```

login.js :
```
function login(email, password, callback) {
	var gatewayURL = @@PG_DOMAIN@@;
	/* ... */
```

a-rule.js :
```
function getPGToken(user, context, callback) {
	var gatewayURL = @@PG_DOMAIN@@;
	/* ... */
```

In the Auth0 dashboard, the values are not replaced, hence the auth flow is broken.

Did I miss something or is it not implemented ?

**Comment by mostekcm** [comment]
I'll check into this.  I'm not sure I had a test case for the .js files.  They should be implemented.  If not I will fix it.

**Comment by mostekcm** [comment]
Once I have this PR merged and released, I can push a new release to auth0-deploy-cli: https://github.com/auth0-extensions/auth0-source-control-extension-tools/pull/8

**Comment by mostekcm** [comment]
@xurei this is now fixed in version 1.0.4 on npm

**Comment by nickcoury** [comment]
@mostekcm I'm still having issues getting this to work.  I looked through all the code and I believe this repo's code never gets the `mappings` object set with `AUTH0_KEYWORD_REPLACE_MAPPINGS`.

The constructor in `context.js` takes `mappings` as the second parameter, but in `index.js`, `context` is only constructed with the first parameter.

Additionally, `auth0-source-control-extension-tools` pulls that info from the config and passes it into `init()`, but again `context.js` ignores that argument.  See [here](https://github.com/auth0-extensions/auth0-source-control-extension-tools/blob/4a5089a4235d66ce51f225dd0769e33d2b30bde9/src/deploy.js#L45).

Am I missing something? I'm trying to replace a keyword in an HTML page and for the life of me can't get it to work as the documentation shows.
